# ── C++23 › Core Language Features ────────────────────────────────────────────
add_subdirectory(deducing_this)
add_subdirectory(if_consteval)
add_subdirectory(multidimensional_subscript)
add_subdirectory(static_call_operator)
add_subdirectory(lambda_attributes)
add_subdirectory(labels_at_end)
add_subdirectory(size_t_literals)
add_subdirectory(auto_decay_copy)
add_subdirectory(constexpr_relaxations)
add_subdirectory(simplified_implicit_move)
add_subdirectory(extended_floating_point)
add_subdirectory(named_universal_char_escapes)
add_subdirectory(delimited_escape_sequences)
add_subdirectory(preprocessor_directives)
add_subdirectory(assume_attribute)
add_subdirectory(utf8_source_encoding)
add_subdirectory(whitespace_in_raw_strings)
