# ── C++14 › Core Language Features ────────────────────────────────────────────
add_subdirectory(generic_lambda)
add_subdirectory(return_type_deduction)
add_subdirectory(relaxed_constexpr)
add_subdirectory(variable_templates)
add_subdirectory(binary_literals)
add_subdirectory(init_capture)
add_subdirectory(decltype_auto)
